WorldSavePath=["/home/leaf/.config/unity3d/IronGate/Valheim", "Saves are located in the 'worlds_local' subdirectory"]
LauncherScriptPath=["/home/leaf/start.sh", "Start a dedicated Valheim server with default password and server name"]
ServerPortList=[[2456, 2457, 2458], "List of public UDP ports the server is listening on by default"]
DiskUsage=[3.0, "GiB"]
MemoryAvgUsage=[3.0, "GiB"]
CPUAvgUsage=[0.25, "Roughly 1/4th of a physical core of an Intel i7 11370H @ 3.2GHz"]
