SavePath=["/root/.config/unity3d/IronGate/Valheim", "Saves are located in the 'worlds_local' subdirectory"]
LauncherScriptPath=["/root/start.sh", "Start dedicated server with default name and password"]
ServerPortList=[[2456, 2457, 2458], "List of public UDP ports the server is listening on by default"]
DiskUsage=[2.0, "GiB"]
MemoryAvgUsage=[2.5, "GiB"]
CPUAvgUsage=[0.25, "Roughly 1/4th of a physical core of an Intel i7 11370H @ 3.2GHz"]
